#pragma once

struct userinput {
	HANDLE Proccssid;
	PVOID address;
	PVOID buffer;
	SIZE_T size;
	PVOID base;
	int inputx;
	int inputy;
	unsigned short button_flags;
	char g_AuthCode[64]; // Updated: String field for authentication code
	const char* name;
};
struct useroutput {
	HANDLE HProcces;
	PVOID returns;
	uintptr_t pml4_base;
	HANDLE VGKHProcces;

	BOOLEAN g_IsAuthenticated = FALSE;

};



#define IOCTL_OPEN_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x14A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_MODULEADDRESS_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x15A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_READ_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x16A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_WRITE_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x17A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_Cr3 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x18A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_Getpmf4 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x19A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_Movemouse CTL_CODE(FILE_DEVICE_UNKNOWN, 0x20A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_SET_AUTH_CODE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x21A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_MODULENAME_CODE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x22A, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)